#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HelloFacebookSample.Resource", IsApplication=true)]

namespace HelloFacebookSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int icon = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int greeting = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int main_ui_container = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int postPhotoButton = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int postStatusUpdateButton = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int profilePicture = 2130837508;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_id = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int cancelled = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int error = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int exception = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int facebook_app_name = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int hello_user = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int no_friends_selected = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int no_place_selected = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int ok = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int permission_not_granted = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int photo_post = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int pick_seattle_place = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int status_update = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int success = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int successfully_posted_post = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int you_picked = 2130968592;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
